---
driver:
  name: vagrant
  network:
    - ["private_network", {ip: "192.168.15.15"}]

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[jen_kins::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
